Apply HSBI stylesheet and update presentation slides
cagix/dlk23 pull request #2
Opened 2023-11-01 18:39 UTC by FinnAmini

So, ich habe jetzt den HSBI Style auf die Präsentation übertragen, die Folien nochmal etwas angepasst und einige Grafiken ergänzt. 
Ich hoffe, dass das alles nach wie vor mit den Lizenzen und der rechtlichen Lage bezüglich der HSBI Foliengestaltung passt.
Die Grafiken und Screenshots die ich ergänzt habe sind auf jeden Fall alle von mir und ich habe versucht darauf zu achten, dass keine fremden Bilder darauf zu sehen sind.

Falls dir optisch etwas nicht gefallen sollte dann halte dich bitte nicht zurück mir das zu sagen. Ich bin leider alles andere als begabt, wenn es darum geht, gestalterisch aktiv zu werden 😅

2023-11-01 19:01 UTC, cagix commented
@FinnAmini  cool, danke dir. das sieht schon richtig gut aus :) 

ist das format wirklich 16:9 (wunsch/anforderung von digikos)? das sieht irgendwie so breit aus?

ein paar kleinigkeiten hab ich noch, das male ich morgen mal ins pdf und poste es hier :)

2023-11-02 06:23 UTC, cagix requested changes
@FinnAmini Noch einmal vielen lieben Dank für die Vorlage! 
Hier ein paar Anmerkungen:

- Ist das Format wirklich 16:9? Das sieht sehr breit aus? (Ich hab grad mal gerechnet, es scheint tatsächlich etwas zu breit zu sein? Oder sind das Rundungsfehler beim Export?)
- Bitte das CC-BY-SA-Logo nicht im Repo einchecken. Wir müssten sonst an geeigneter Stelle entsprechende Urheber-Hinweise einbauen. Ich verwende es dynamisch, d.h. es wird bei mir immer per Link eingebunden. Im PPTX/PDF ist es afaik aber ok, da muss man nicht noch einen extra Hinweis haben.
- Für die Folien habe ich meine Anmerkungen mal direkt in das PDF gemalt. Teilweise sind es kleine Tippfehler, teilweise kleinere Formatierungen. Schau mal, was Du davon übernehmen/umsetzen willst.
- Die Screenshots sind teilweise schwer lesbar. Wir haben den horizontalen Platz auf der Folie jeweils genutzt, aber vertikal wäre noch Spielraum. Wenn Du die angemerkten Screenshots nochmal aufnimmst mit einem schmaleren Browserfenster (also die Screenshots an sich schmaler werden), dann nutzen sie auf der Folie auch den vertikalen Platz besser und der Text wird größer/lesbarer.

Annotierte Folien: [peer-feedback.pdf](https://github.com/cagix/dlk23/files/13235001/peer-feedback.pdf)

2023-11-02 06:23 UTC, cagix commented on img/license.png
Diese Datei bitte nicht einchecken - die stammt nicht von uns und müsste extra deklariert werden (im Repo). Es reicht, wenn wir die dynamisch einbinden (Markdown, Latex&Beamer) bzw. manuell in das PPTX reintun.

2023-11-02 19:37 UTC, FinnAmini commented
> @FinnAmini Noch einmal vielen lieben Dank für die Vorlage! Hier ein paar Anmerkungen:
> 
> * Ist das Format wirklich 16:9? Das sieht sehr breit aus? (Ich hab grad mal gerechnet, es scheint tatsächlich etwas zu breit zu sein? Oder sind das Rundungsfehler beim Export?)
> * Bitte das CC-BY-SA-Logo nicht im Repo einchecken. Wir müssten sonst an geeigneter Stelle entsprechende Urheber-Hinweise einbauen. Ich verwende es dynamisch, d.h. es wird bei mir immer per Link eingebunden. Im PPTX/PDF ist es afaik aber ok, da muss man nicht noch einen extra Hinweis haben.
> * Für die Folien habe ich meine Anmerkungen mal direkt in das PDF gemalt. Teilweise sind es kleine Tippfehler, teilweise kleinere Formatierungen. Schau mal, was Du davon übernehmen/umsetzen willst.
> * Die Screenshots sind teilweise schwer lesbar. Wir haben den horizontalen Platz auf der Folie jeweils genutzt, aber vertikal wäre noch Spielraum. Wenn Du die angemerkten Screenshots nochmal aufnimmst mit einem schmaleren Browserfenster (also die Screenshots an sich schmaler werden), dann nutzen sie auf der Folie auch den vertikalen Platz besser und der Text wird größer/lesbarer.
> 
> Annotierte Folien: [peer-feedback.pdf](https://github.com/cagix/dlk23/files/13235001/peer-feedback.pdf)

@cagix Vielen Dank für das Feedback!
Ich habe jetzt die Änderungsvorschläge umgesetzt und die Folien nochmal überarbeitet. Die Screenshots habe auch nochmal aufgenommen, im Falle der Kriterienkataloge habe ich jetzt Text statt Screenshots genutzt, da es so noch leserlicher ist. 

Ich habe auch nochmal das Format der Präsentation überprüft, aber es war tatsächlich schon 16:9 eingestellt. Um sicher zu gehen habe ich die Folien in der pdf zusätzlich noch mit einem Bildschirmlineal ausgemessen, wobei Maße von 1280x720 Pixel rausgekommen sind, was einem Format von 16:9 entspricht. Kann es sein, dass deine Bildschirmeinstellungen evtl. etwas irreführend sind? Mir ist aufgefallen, dass deine Screenshots auch relativ quadratisch waren, vielleicht hängt das ja damit zusammen. :)

2023-11-03 09:29 UTC, cagix requested changes
@FinnAmini Hey, super!

Noch drei kleine Sachen/Änderungswünsche:

- Folie "Lessons Learned", letzter Stichpunkt: kein Komma bei "... das Feedback fehlt an ..."
- Bilder bei "Einrichtung des Kursraums": Folie "ADMIN" und Folie "BENUTZER": Im Vergleich finde ich die Bilder vom letzten Mal doch besser. Kannst Du die aus dem letzten Commit bitte nochmal rausfischen und ersetzen?
- Folie "Offener Kursraum Compilerbau", letzter Stichpunkt sollte heissen "Versteckt: Selbsttests"

2023-11-03 09:35 UTC, cagix commented
> @cagix Vielen Dank für das Feedback! Ich habe jetzt die Änderungsvorschläge umgesetzt und die Folien nochmal überarbeitet. Die Screenshots habe auch nochmal aufgenommen, im Falle der Kriterienkataloge habe ich jetzt Text statt Screenshots genutzt, da es so noch leserlicher 

Bei den Kriterienkatalogen stimme ich Dir zu - das liest sich jetzt besser!

Bei den beiden Folien zur Einrichtung (Admin, Benutzer) finde ich im Vergleich die ursprünglichen Screenshots doch besser. Kannst Du bei den beiden bitte nochmal zurückrudern (wenn Du das auch so siehst)?


> Ich habe auch nochmal das Format der Präsentation überprüft, aber es war tatsächlich schon 16:9 eingestellt. Um sicher zu gehen habe ich die Folien in der pdf zusätzlich noch mit einem Bildschirmlineal ausgemessen, wobei Maße von 1280x720 Pixel rausgekommen sind, was einem Format von 16:9 entspricht. Kann es sein, dass deine Bildschirmeinstellungen evtl. etwas irreführend sind? Mir ist aufgefallen, dass deine Screenshots auch relativ quadratisch waren, vielleicht hängt das ja damit zusammen. :)

Hehe ... Ich mache normalerweise eher relativ quadratische Screenshots, weil bei den superbreiten Screenshots normalerweise auf den Folien oben und unten drunter viel Freiraum ist - wenn die Screenshots etwas schmaler sind, wird dieser Platz auf den Folien für die Abbildung genutzt und dadurch werden die Sachen größer und besser lesbar. 

Ich hatte in den Datei-Informationen zum PDF nachgeschaut, und da stand 33,87x19,05 cm, also 16:8.9 ... also eher Rundungsfehler. 

Ich glaube, ich weiss jetzt, warum mir das so extrem breit vorkommt: Auf dem Mac sind die Bildschirme normalerweise 16:10 und entsprechend habe ich meine Folien auch immer 16:10 ... Das wird wohl der Grund gewesen sein. Sorry, dass ich Dich da nochmal auf eine falsche Fährte gelockt habe!

2023-11-03 09:46 UTC, cagix commented on img/digikos_logo.png
Das DigikoS-Logo dürfen wir auch nicht einchecken. Sry, dass hatte ich übersehen!

2023-11-03 15:07 UTC, FinnAmini commented
> @FinnAmini Hey, super!
> 
> Noch drei kleine Sachen/Änderungswünsche:
> 
> * Folie "Lessons Learned", letzter Stichpunkt: kein Komma bei "... das Feedback fehlt an ..."
> * Bilder bei "Einrichtung des Kursraums": Folie "ADMIN" und Folie "BENUTZER": Im Vergleich finde ich die Bilder vom letzten Mal doch besser. Kannst Du die aus dem letzten Commit bitte nochmal rausfischen und ersetzen?
> * Folie "Offener Kursraum Compilerbau", letzter Stichpunkt sollte heissen "Versteckt: Selbsttests"

Fertig :)

2023-11-03 15:09 UTC, FinnAmini commented
> > @cagix Vielen Dank für das Feedback! Ich habe jetzt die Änderungsvorschläge umgesetzt und die Folien nochmal überarbeitet. Die Screenshots habe auch nochmal aufgenommen, im Falle der Kriterienkataloge habe ich jetzt Text statt Screenshots genutzt, da es so noch leserlicher
> 
> Bei den Kriterienkatalogen stimme ich Dir zu - das liest sich jetzt besser!
> 
> Bei den beiden Folien zur Einrichtung (Admin, Benutzer) finde ich im Vergleich die ursprünglichen Screenshots doch besser. Kannst Du bei den beiden bitte nochmal zurückrudern (wenn Du das auch so siehst)?
> 
> > Ich habe auch nochmal das Format der Präsentation überprüft, aber es war tatsächlich schon 16:9 eingestellt. Um sicher zu gehen habe ich die Folien in der pdf zusätzlich noch mit einem Bildschirmlineal ausgemessen, wobei Maße von 1280x720 Pixel rausgekommen sind, was einem Format von 16:9 entspricht. Kann es sein, dass deine Bildschirmeinstellungen evtl. etwas irreführend sind? Mir ist aufgefallen, dass deine Screenshots auch relativ quadratisch waren, vielleicht hängt das ja damit zusammen. :)
> 
> Hehe ... Ich mache normalerweise eher relativ quadratische Screenshots, weil bei den superbreiten Screenshots normalerweise auf den Folien oben und unten drunter viel Freiraum ist - wenn die Screenshots etwas schmaler sind, wird dieser Platz auf den Folien für die Abbildung genutzt und dadurch werden die Sachen größer und besser lesbar.
> 
> Ich hatte in den Datei-Informationen zum PDF nachgeschaut, und da stand 33,87x19,05 cm, also 16:8.9 ... also eher Rundungsfehler.
> 
> Ich glaube, ich weiss jetzt, warum mir das so extrem breit vorkommt: Auf dem Mac sind die Bildschirme normalerweise 16:10 und entsprechend habe ich meine Folien auch immer 16:10 ... Das wird wohl der Grund gewesen sein. Sorry, dass ich Dich da nochmal auf eine falsche Fährte gelockt habe!

Das klingt logisch. Was die Screenshots an sich angeht, muss ich auch ehrlich zugeben, dass deine Screenshots deutlich schöner sind... Insbesondere die Box-Shadows machen das ganze nochmal deutlich ansprechender.

2023-11-03 15:09 UTC, FinnAmini commented on img/digikos_logo.png
Stimmt! Ist weg.

2023-11-03 16:28 UTC, cagix approved these changes
good job 👍 mange tak! 👏

2023-11-03 16:29 UTC, cagix commented
@FinnAmini super! das sieht echt gut aus. danke dir 🙏

2023-11-03 16:35 UTC, merged